#+TITLE: Take home exams Week2 Marcelo Veloso Maciel


* Them 3.1
** 1
They are comparing the whole group, men, average with a subgroup average which was already taken into account when calculating the whole group average. A better comparison would be between the subgroup of orchestra conductors versus its complement.  Nevertheless, the comparison would still be fraught with difficulties and would require some kind of matching between the units of those two groups.
** 2
There are confounders. The argument is that orchestra conducting has an effect on life expectancy. However, if you remember that social class has an effect on the probability of being an orchestra conductor and on life expectancy the previous causal relationship between orchestra conducting and life expectancy will likely turn out to be spurious. Thus, I would control for this confounder. A regression which added the variable 'social class' would likely suffice.

* Them 3.2
** 1
(0.99 * 0.8) + (0.01 * 0.1) = 0.793
** 2
(0.001)/0.793 = 0.00126
** 3
In the text it seems to be P(I|A) =
(0.009)/(0.198 + 0.009)= 0.043; in the hint it says that what is being asked is P(A|I), that is given in the problem statement: given that the Judge considers someone is innocent the probability of someone being acquitted is 0.9.
* Them 3.3
I'll do both parts at the same time. Missing in those tables are the proportion of papers that got rejected per field. That is, though 38% of the papers that got accepted were about comparative politics it is possible that the volume of papers submitted in this area is very high. On the other hand, though formal theory only accounts for 3% of the accepted papers by field the volume of papers submitted in this field is likely to be very low in comparison to other areas. All in all, what would I choose given the information in the tables? For each observation I would need to input the missing rejection information. Then I would multiply the probability of being accepted with the ratio of each field/approach. Given that the discipline focuses on the three main fields (comparative / national politics / international relations) and mostly trains quantitative researchers I believe that a combination of Normative Theory or Formal Theory field and Formal or Interpretive approach would be a safer bet.

* Them 3.4

1. p = 0.5, n = 7,  k = 4, thus Pr(X>=k) = 0.5
2. p = 0.5, n = 6, k = 4,  thus Pr(X>=k) = 0.344
3. p = 0.5, n = 5, k = 3, thus Pr(X>=k) = 0.5
4. p = 0.5, n = 4, k = 3, thus Pr(X>=k) = 0.313
5. p = 0.5, n = 3, k = 3, thus Pr(X>=k) = 0.125
6. The probability is zero. They have already lost 4 games.

Source code for the exercise:
#+begin_src julia :export false
using Distributions
winningprob(n,k,p) = sum(pdf(Binomial(n,p), i) for i in k:n)

# 1. p = 0.5, n = 7, k = 4, thus Pr(X>=k) =
winningprob(7,4,0.5)

# 2. p = 0.5, n = 6, k = 4, thus Pr(X>=k) =
winningprob(6,4,0.5)

# 3. p = 0.5, n = 5, k = 3, thus Pr(X>=k) =
winningprob(5,3,0.5)

# 4.  p = 0.5, n = 4, k = 3, thus Pr(X>=k)
winningprob(4,3,0.5)

# 5. p = 0.5, n = 3, k = 3, thus Pr(X>=k) =
winningprob(3,3,0.5)

#+end_src


* Them 3.7

** 1
*** a
I should bet red. The previous round has no effect on the subsequent round, and as such one should choose red as it has the highest probability of showing up.
*** b
On average I would expect to win 80 dollars (200 * 0.6 - 100*0.4)
** 2
*** a
Same as 1.a. I should bet red.
*** b
Same as 1.b. I would expect to win 80 dollars.
** 3
Yes, it does. My chance of winning is consistently bigger than my chance of losing.

** 4
I should bet white. The expected payoff is 35 * 0.1 - 2*0.9 = 1.7, while the expected payoff of the other colors is 0.8.

* Them 3.8
I do not understand how to translate this question into a decision tree.


* Them 3.9
I could not get the table from the slide. I tried many ways.

* Them 4.1
On the first plot one sees two patters: the american death rate is much higher than the OECD general pattern. Moreover, it has been declining. I don't know enough about the american society to concoct an hypothesis for the second pattern, but the first could be the following: the more lenient the gun permit laws of a country the higher its death rate.

For the second plot there are three patterns. The higher the population the lower the proportion of covid first dose. The higher the population the lower the republican vote share. The higher the republican vote share the lower the proportion of covid first dose. An ambitious hypothesis for the second pattern could be: the higher the urban complexity of a place the lower the conservative values within that place. Urban complexity is associated with higher population sizes, but also, and that is an hypothesis in itself, with higher adhesion to cultural liberal values, which leads to lower votes to republicans.


* Them 4.2
It depends on how much a student values the minor. It is analogous to elasticity. If a student deems too costly to take another course in political science to get the minor he can simply switch to another minor. So, the addition of one new course may or may not lead a single student to leave the minor. Call that the elasticity of getting the minor. If the average student choice to remain pursuing the minor is inelastic to the addition of new courses the new requirement will indeed lead to more political science courses being taken. If the average student choice of pursuing the minor  is elastic to the addition of new courses then the new requirement may backfire and lead to even less undergraduate students taking political science courses, since the average student will simply cease taking *any* courses in political, given that it has switched to another minor.

* Them 4.3
The case in which both are not using a mask. This case would likely show a very high contagion probability, which would dissuade people from not using a mask for two reasons: they would infect others with a high probability if they are infected and they would get infected by another infected person with a high probability too.

* Them 4.4
It seems to be again a binomial distribution problem. If we let \(p  = 0.5\) and \(n = 120\) and \(k = 60\) then \(P(k=60) = 0.073\)

#+begin_src julia
using Distributions

pdf(Binomial(120,0.5), 60) # =>    0.07268497891011672
#+end_src

* Them 4.5

It is harder to detect cancer in women with dense breasts because the proportion of women with dense breasts is low. However, within this subsample the proportion of women whose identified death cause was cancer is greater than in the set of women with non-dense breasts. Thus, it is harder to detect while being more likely.
